### ISSUE TITLE
[QUESTION] 服务器中，背包物品图标显示问题。

### ISSUE THREAD

**Issue by Yuzaihhhh** [Arcomua-Modpack/Arcomua-Modpack#10]
我在使用 Arcomua 整合包在多人服务器游玩过程中发现，背包中物品显示的是Minecraft原版的图标，而不是服务器资源包的样式。

我想让背包中物品显示为服务器资源包的样式，我应该如何操作？

**Screenshots**
![Snipaste_2024-01-30_13-34-46](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/4573af83-8a75-4d12-a859-bafae14acc83)
![Snipaste_2024-01-30_13-35-26](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/0b99733c-6433-43e8-b8c9-f77625423132)
![Snipaste_2024-01-30_13-37-07](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/1009a4a4-d7f7-4f14-91c8-5872966808f9)
![Snipaste_2024-01-30_13-37-48](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/9022bb90-fac0-4c70-933b-71890d381f42)
![Snipaste_2024-01-30_13-56-43](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/14b6e682-262e-4f71-95bd-02e9f3235c53)

**Environment (please complete the following information):**
 - OS: [Windows 10 22H2 (19045.3930)]
 - Modpack Version: [1.20.4 Fabric 240122]
 - Java Version: [OpenJDK Runtime Environment Temurin-17.0.10+7 64-Bit]

**Comment by Trcmoe** [comment]
已经收到了您的反馈，正在尝试复现并溯源。

**Comment by Yuzaihhhh** [comment]
找到了原因了，[Eating Animation](https://modrinth.com/mod/eating-animation) 这个mod导致的。

**Comment by Trcmoe** [comment]
感谢您的反馈，这几天由于过年的事情无法使用电脑，没有及时处理该问题，请见谅。

由于该模组没有提供配置文件以供调整，出于对“保持原版功能完整”的考虑，我们决定在之后的版本中移除该模组。再次感谢您的反馈。
