### ISSUE TITLE
[BUG] 服务器自定义的皮革盔甲渲染问题

### ISSUE THREAD

**Issue by Yuzaihhhh** [Arcomua-Modpack/Arcomua-Modpack#11]
**Describe the bug**
我游玩的服务器是有他自己的定制内容的，譬如说截图中的透明套装，用于隐藏盔甲。当然，这个服务器是原版服，所以定制内容并非像forge或者farbric那种。
然后服务器里有个发光特效，就是被光灵箭射中后的那种特效。
我把发光特效打开之后，发现每个玩家都会有“毛刺”，如截图。如果我再把光影打开，就会出现像纹理错误一样的效果，如截图。

我尝试更换光影，问题依旧。

**Screenshots**
![Snipaste_2024-02-25_00-58-14](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/a4cfbcf3-4fde-448a-b3ce-e5c2c4671e43)
![Snipaste_2024-02-25_00-59-27](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/f9d4c9f8-ac70-4885-8630-97810ca7ef74)
![Snipaste_2024-02-25_01-00-22](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/ab69f3a8-f277-4c68-993c-fd54042a6803)
问题截图

![Snipaste_2024-02-25_01-01-55](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/ef0edb0a-b6da-4be6-87a8-114828de7591)
![Snipaste_2024-02-25_01-02-11](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/8b9c574b-6657-4963-a7ce-79ba7492f7c0)
![Snipaste_2024-02-25_01-02-41](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/2f9bf2a7-83bd-4808-a8ba-dc946e46da92)
装备截图

---

![Snipaste_2024-02-25_01-27-17](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/66c49a50-0e7f-4b02-ac99-85bea17b7be5)
![Snipaste_2024-02-25_01-31-52](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/26414906-9f6e-4ed2-b8b1-45ca5f2e698a)
有光影

![Snipaste_2024-02-25_01-26-10](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/16d46ae4-d77b-46aa-aab0-2fb2a269d519)
![Snipaste_2024-02-25_01-27-02](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/017ed23c-efff-41de-bcd6-a940306e3973)
无光影

![Snipaste_2024-02-25_01-09-01](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/ec9be864-fb53-4aa7-95bb-82429bed8645)
![Snipaste_2024-02-25_01-09-08](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/b676fb68-9f9f-45ef-a794-dcc59f043b34)
![Snipaste_2024-02-25_01-09-14](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/f7d0518e-7af0-4100-8b89-524d0277d7c1)
![Snipaste_2024-02-25_01-09-20](https://github.com/Arcomua-Team/Arcomua-Modpack/assets/29204544/cd4d71b0-19c0-439b-9431-1ebc300cfdd3)
装备截图

---

**Environment (please complete the following information):**
- OS: [Windows 10 22H2 (19045.4046)]
- Modpack Version: [1.20.4 Fabric 240122]
- Java Version: [OpenJDK Runtime Environment Temurin-17.0.10+7 64-Bit]

**Comment by Trcmoe** [comment]
你可以试着禁用模组[3D Skin Layers](https://modrinth.com/mod/3dskinlayers)或[Show Me Your Skin!](https://modrinth.com/mod/show-me-your-skin)，这两款模组对玩家皮肤有一定程度的修改，可能与您遇到的问题有关。

**Comment by Yuzaihhhh** [comment]
两个模组均删除，问题依旧

**Comment by Trcmoe** [comment]
那我估计此问题可能与渲染相关的模组或OptiFine代替品模组有关系，可以用二分法的方式排查一下是哪个模组导致了这个问题。

**Comment by Yuzaihhhh** [comment]
已经找到原因, 是因为缺少[CIT Resewn](https://modrinth.com/mod/cit-resewn)模组导致的.
是使用<Arcomua Modpack 1.20.1-fabric-240220>排查发现的.
