### ISSUE TITLE
[BUG] Playerlist dosen't update information

### ISSUE THREAD

**Issue by Da-Docta** [Arcomua-Modpack/Arcomua-Modpack#12]
**Describe the bug**
On version 1.20.2 Fabric 240223 the player list only loads once you join the first server and won't update until you close the game

**Environment (please complete the following information):**
 - OS: Windows 11
 - OS Version: 23H2
 - Modpack Version: Fabric 240223

**Comment by Trcmoe** [comment]
Can you record a video of it?

**Comment by Trcmoe** [comment]
You can try to disable [Exordium](https://modrinth.com/mod/exordium) to see if the problem still exists. If no further information is provided, I will close this issue.
