### ISSUE TITLE
[BUG] Extremely choppy when using the TitleChanger mod

### ISSUE THREAD

**Issue by Theblockbuster1** [Arcomua-Modpack/Arcomua-Modpack#13]
**Describe the bug**
The FPS dramatically drops whenever the mouse is moved, making it incredibly difficult to play. After testing, I found that the problem only occurs when the [TitleChanger](https://modrinth.com/mod/mctitlechanger) mod is being used. I fixed it by simply disabling the mod in ATLauncher, and also the [LinsAPI](https://modrinth.com/mod/linsapi) mod, which is just a dependency.

Otherwise, very useful modpack :)👍 

**To Reproduce**
1. Install the modpack (240508)
2. Load into any singleplayer world
3. Check the FPS
4. Move your mouse, and see that the FPS should drop extremely low

**Expected behavior**
The FPS should stay high.

**Environment (please complete the following information):**
 - OS: Windows 11
 - OS Version 23H2
 - Modpack Version: Fabric 240508
 - Java Version: Java 21.0.3

**Additional context**
ATLauncher logs: https://paste.atlauncher.com/view/6fd814bb-5335-4b4d-826e-b1b2348dc4a2
I loaded into a Skyblock world, and then also created a new flat world, and the problem occurred on both.

**Comment by Trcmoe** [comment]
Thank you for your feedback. I've confirmed the issue and be prepared to replace it with another title change mod in later releases.

**Comment by Trcmoe** [comment]
Fixed in [1.20.6-fabric-240611](https://modrinth.com/modpack/arcomua/version/ZdNRM0e8).
