### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by A5yncX** [Arcomua-Modpack/Arcomua-Modpack#14]
**Describe the bug**
使用整合包进入服务器后, 大多数玩家的发言不可见, 在delete了一些chat的mod后发现会自动下载回来

**Screenshots**
为了可见, 我开启了时间戳
<img width="505" alt="image" src="https://github.com/Arcomua/Arcomua-Modpack/assets/54523269/fd68806d-5a2b-46af-8965-1b3d95a94619">

**Environment (please complete the following information):**
 - OS: MacOS Sonoma
 - Minecraft Version 1.20.4
 - Java Version: 17

**想寻求的帮助**
- 是由哪个mod导致的吗?
- 如果是由mod导致的, 我该怎么停用那个mod并防止启用?

**Comment by Trcmoe** [comment]
我想知道服务器的情况（比如是否启用聊天验证，是否开启正版验证），以及你具体禁用了哪些模组才解决了这种情况的发生。

**Comment by A5yncX** [comment]
> 我想知道服务器的情况（比如是否启用聊天验证，是否开启正版验证），以及你具体禁用了哪些模组才解决了这种情况的发生。

服务器开启了正版验证, 在进入后有弹出"聊天是不安全的"我认为没有启用聊天验证, 我试图禁用了带有chat一词的mod, 情况并没有解决, 因为在开启游戏时整合包自动下载回来并启用了.
我在更换了Lite整合包后 一切正常了.

**Comment by Trcmoe** [comment]
最近测试的时候发现，使用Xaero世界地图向聊天栏分享位点时会无法显示，检查后发现可能是与模组“ChatPatches”发生冲突，之后会想办法解决该问题。
