### ISSUE TITLE
[BUG]EMI cause crashes on Arcomua ModPack Cloth ver. 240617

### ISSUE THREAD

**Issue by aloysius4831** [Arcomua-Modpack/Arcomua-Modpack#15]
**To Reproduce**
使用BakaXL启动游戏，先进入一次外部服务器，再进入一个本地存档。
如果EMI正常被加载，打开物品栏时游戏崩溃（第二个崩溃日志）
如果不加载EMI，使用REI替代EMI，离开存档时游戏崩溃（同样可在EMI被正常加载时复现）
两者都是偶发性问题。

**Expected behavior**
游戏崩溃，给出两种不同的错误日志。

**Environment**
 - OS: Windows 11 Professional
 - OS Version 23H3 Build 22621.3668
 - Minecraft Version 1.21.0
 - Modpack Version: Cloth 240617
 - Java Version: Zulu21.34.19

**Crash report**
[crashreport.txt](https://github.com/user-attachments/files/16038775/crashreport.txt)

**Additional Files and Words**
这里是出现问题的存档。[一桶岩浆生炸74k刷石机.zip](https://github.com/user-attachments/files/16038764/74k.zip)
我只在这个存档中发现了按E键游戏崩溃的问题。请注意：崩溃时使用投影加载了一个投影文件。

**Comment by Trcmoe** [comment]
我看了日志，感觉是Carpet的问题，这边有一个基本相同的[issue](https://github.com/gnembon/fabric-carpet/issues/1908)。

**Comment by aloysius4831** [comment]
有看到，但里面提交的代码应该是还没合入到Carpet本体
至于EMI导致游戏崩溃的问题我自己测试下来确实是换用REI可以解决的，希望可以在后续版本改用REI

**Comment by Trcmoe** [comment]
Fixed in 1.21-fabric-240810.
