### ISSUE TITLE
[BUG]按“/”打开聊天时，输入法无法切换成中文

### ISSUE THREAD

**Issue by Many-LIN** [Arcomua-Modpack/Arcomua-Modpack#16]
**Describe the bug**
按“/”打开聊天时，输入法无法切换成中文
而按“T”打开的聊天无此问题
原版mc 1.21无此问题

**Environment (please complete the following information):**
 - OS: Windows10
 - OS Version 21H2
 - Minecraft Version 1.21
 - Modpack Version: Fabric 240810
 - Java Version: Zulu JRE 21 64-bit

**Comment by Many-LIN** [comment]
补充：在其他输入框，如模组设置中的搜索框，也会出现这种问题

**Comment by Trcmoe** [comment]
该功能可以在IMBlocker的模组设置中选择关闭。
