### ISSUE TITLE
[REQUEST] Change "low TPS" to "high TPS" in Modrinth description because low TPS is bad.

### ISSUE THREAD

**Issue by xxtarfall** [Arcomua-Modpack/Arcomua-Modpack#17]
**Is your feature request related to a problem? Please describe.**
"low TPS" text makes modpack look bad because low TPS (1 to +-15) is bad.

**Describe the solution you'd like**
Change
"# ⚡️ High-Performance
Arcomua Cloth includes a lot of optimization mods. High FPS, low TPS, and fast world loading become possible."
To
"# ⚡️ High-Performance
Arcomua Cloth includes a lot of optimization mods. High FPS and TPS, and fast world loading become possible."

**Describe alternatives you've considered**
No alternative solutions lmao.

**Additional context**
idk from google:
> A higher TPS value indicates that the server is running more efficiently, with faster processing and fewer delays. On the other hand, a lower TPS can result in lag, delayed actions, and a less enjoyable gameplay experience for players.

Source: minesite.org

**Comment by Trcmoe** [comment]
Fixed, thanks for pointing out the misuse of words.
