### ISSUE TITLE
Wrong Music Replay in Game

### ISSUE THREAD

**Issue by NekoCompiler** [Arcomua-Modpack/Arcomua-Modpack#4]
1.20.1 - Fabric 230720 有个 bug ，单人游戏内播放的音乐是主界面的音乐。

**Comment by NekoCompiler** [comment]
希望尽快修复，整合包导入方式：modrinth (.mrpack) ，启动器：Prism Launcher ，Java版本：Oracle JDK 17.0.8

**Comment by NekoCompiler** [comment]
音乐的音量默认是禁用的，被我开了。

**Comment by Trcmoe** [comment]
After playing an hour in this version with the same launcher, I didn't meet this problem.

If you'd like to follow up on this issue, we suggest you upload some game logs to help us analyze the problem.

Also, the title menu has 4 BGMs, according to the [Minecraft Wiki](https://minecraft.fandom.com/wiki/Music#Extras). If you insist that you heard these BGMs wrong place, you probably need to consult a trusted physician about whether your hormone medicines have hallucinogenic ingredients in them.

**Comment by NekoCompiler** [comment]
国创整合包有你更精彩

**Comment by Trcmoe** [comment]
![ddc6d137a672517ab9dccdb092ddc2fd.jpeg](https://i.mji.rip/2023/07/29/ddc6d137a672517ab9dccdb092ddc2fd.jpeg)
Please put yourself in my shoes.

首先我问你用的什么模组加载器，是因为我们同时提供了Forge、Fabric和Quilt版本，我需要知道具体是哪一个版本存在此问题。其次，我说默认把音乐关了仅仅只是为了陈述一个事实，你上来一句“你不听有人听”，好悬没让我绷得住。

就你这提交问题的态度，还想让我以礼相待，那我只能说你吃糖吃的。

另外既然你声称自己已经“弃包”，那此问题修不修也没有意义了。感谢您的不支持与理解。
