### ISSUE TITLE
为什么我已经把背包整理删了在背包里按r还会整理背包啊?

### ISSUE THREAD

**Issue by Redapple-one** [Arcomua-Modpack/Arcomua-Modpack#5]

**Comment by Trcmoe** [comment]
Please provide the version you are using.

**Comment by Redapple-one** [comment]
1.20.1 fabric

**Comment by Trcmoe** [comment]
I didn't have the same problem. Did you modify the modpack?
Also, the R key is already being held by Bedrodium. This mod didn't provide the function you mentioned.

If you press R against an item in your backpack, it will only take you to the EMI Loot that the mod used to determine how to get items.

Just so you know, some servers install auto-organizing plugins, and if this problem happens in multiplayer mode, then you should ask the server owner about this issue.

 If you still have questions, you can attach more descriptions of the problem. If not, you can close this issue.

**Comment by Redapple-one** [comment]
OK
Thanks
