### ISSUE TITLE
Add Mod - CalcMod

### ISSUE THREAD

**Issue by shadeydo** [Arcomua-Modpack/Arcomua-Modpack#6]
Add the mod [CalcMod](https://modrinth.com/mod/calcmod), A simple clientside calculator in the minecraft chat, with extra shortcuts to make life easier. i think it would really fit the "vanilla QoL" vibe of Arcomua, as its unintrusive but handy!
see a full list of features in the modrinth listing above!

**Comment by Trcmoe** [comment]
The mod does look great, but I don't currently think the mod goes well with our modpacks. Users will need to learn to use this calculation mod, which might not be as convenient as just opening the calculator program on your computer.
