### ISSUE TITLE
1.20.1 Fabric 230816 Apple Silicon 无法启动游戏，一直提示Java崩溃

### ISSUE THREAD

**Issue by hosizoraru** [Arcomua-Modpack/Arcomua-Modpack#7]
<img width="1112" alt="截屏2023-09-06 21 26 13" src="https://github.com/Arcomua-Modpack/Arcomua-Modpack/assets/63982994/2ef5029c-cf11-4539-846d-0dfd886ef15f">
首先先贴上版本号：
<img width="1392" alt="截屏2023-09-06 21 18 24" src="https://github.com/Arcomua-Modpack/Arcomua-Modpack/assets/63982994/4728d5e6-0870-4db9-bb5b-df796e6b6494">
<img width="1392" alt="截屏2023-09-06 21 18 54" src="https://github.com/Arcomua-Modpack/Arcomua-Modpack/assets/63982994/512a9889-cc0c-4421-975a-d4b9a2d06715">
log会在最后展示，接下来是展示其他环境：
<img width="1392" alt="截屏2023-09-06 21 19 04" src="https://github.com/Arcomua-Modpack/Arcomua-Modpack/assets/63982994/c1527745-b151-4234-86e0-6c712c901218">
机器是 MacBook Pro 16英寸 2023版本，Soc是Apple Slicon M2 Pro，配置是32+1t，系统是macOS Sonoma Beta7 （23A5337a）,运存我分配了8172MB
Java版本使用了Modrinth自带的Java17或者我从Oracle官网下载的Java20都不行。
<img width="478" alt="截屏2023-09-06 21 27 26" src="https://github.com/Arcomua-Modpack/Arcomua-Modpack/assets/63982994/68f9a80c-0f4a-430c-b8c6-2683e41c0fbc">
<img width="479" alt="截屏2023-09-06 21 28 06" src="https://github.com/Arcomua-Modpack/Arcomua-Modpack/assets/63982994/13db5a6a-afea-4a7a-8c73-a0a3a4abff0e">
<img width="838" alt="截屏2023-09-06 21 22 24" src="https://github.com/Arcomua-Modpack/Arcomua-Modpack/assets/63982994/b4026a01-7e6d-47e6-863a-33e0278d9bdb">
以下是Modrinth里的Logs：
[logs.txt](https://github.com/Arcomua-Modpack/Arcomua-Modpack/files/12537794/logs.txt)

**Comment by Trcmoe** [comment]
我们已经收到了您提交的问题，感谢您的反馈。

我们目前还没有ARM的macOS测试环境，您的问题可能需要一段时间以解决，我们在努力寻找解决方案。

**Comment by hosizoraru** [comment]
经过排查和测试，发现是以下这个mod的问题：
forcegl20-fabric-1.1.0
如果其他Apple silicon用户也遇到了相同的问题，可以把这个mod去掉

**Comment by Trcmoe** [comment]
已经确认问题所在，主要原因在于ForceGL20修改了游戏使用的OpenGL版本造成了部分平台不兼容。

解决方法是删除`forcegl20-fabric-1.1.0.jar`。
