### ISSUE TITLE
[BUG] Crash on Ubuntu 23.10

### ISSUE THREAD

**Issue by Mr-Python-in-China** [Arcomua-Modpack/Arcomua-Modpack#8]
启动器：HMCL v3.5.5

版本：1.20.2 - Fabric	

操作步骤：

https://github.com/Arcomua-Team/Arcomua-Modpack/assets/89737170/ec92f26e-cd87-4572-a7ea-c0aa8cb758e6

报错：
[minecraft-exported-crash-info-2023-11-25T20-00-15.zip](https://github.com/Arcomua-Team/Arcomua-Modpack/files/13464092/minecraft-exported-crash-info-2023-11-25T20-00-15.zip)

系统：ubuntu 23.10
```
Linux MP-ThinkPad 6.5.0-13-generic #13-Ubuntu SMP PREEMPT_DYNAMIC Fri Nov  3 12:16:05 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Trcmoe** [comment]
已确认 Puzzle 与 Entity Model Features 或 Entity Texture Features 之间存在一个会导致游戏崩溃的问题，你可以在[这里](https://github.com/PuzzleMC/Puzzle/issues/73)查看更多信息。

我们正在等候 Puzzle 的作者解决此问题，在这之前，我们会禁用掉 Puzzle 按钮以防止玩家误触造成崩溃。

**Comment by Trcmoe** [comment]
Fixed in 231130 (by disabling the "Puzzle" button in default).
