### ISSUE TITLE
[ERROR]添加mod导致崩溃

### ISSUE THREAD

**Issue by Yao961230** [Arcomua-Modpack/Arcomua-Modpack#9]
[错误报告.zip](https://github.com/Arcomua-Team/Arcomua-Modpack/files/13698290/default.zip)
加入FTP连锁破坏会崩溃无法启动，论坛发帖也暂时无人回答，求助

**Comment by Trcmoe** [comment]
你的FTB Ultimine版本太旧了，请更新。
